version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: barberred_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: barber_user
      POSTGRES_PASSWORD: barber_password
      POSTGRES_DB: barberred_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
